#!/bin/bash

echo "🚀 College Portal - GitHub Setup Script"
echo "========================================"

# Set git user config (run once)
echo "Setting up git configuration..."
read -p "Enter your name: " GIT_NAME
read -p "Enter your email: " GIT_EMAIL
git config user.name "$GIT_NAME"
git config user.email "$GIT_EMAIL"

# Commit all files
echo "Committing files..."
git add -A
git commit -m "College Portal - Complete Flask application with all services"

echo ""
echo "✅ Git repository is ready!"
echo ""
echo "📋 NEXT STEPS TO COMPLETE DEPLOYMENT:"
echo "====================================="
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to: https://github.com/new"
echo "   - Repository name: college-portal"
echo "   - Description: College Portal - Student Services App"
echo "   - Make it Public or Private"
echo "   - DO NOT check 'Add a README'"
echo "   - Click 'Create repository'"
echo ""
echo "2. Push your code (copy and run these commands):"
echo ""
echo "   git remote add origin https://github.com/Rishi2003-cpu/college-portal.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Render.com:"
echo "   - Go to: https://render.com"
echo "   - Sign up with GitHub"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Select your 'college-portal' repository"
echo "   - Configure:"
echo "     * Name: college-portal"
echo "     * Build Command: pip install -r requirements.txt"
echo "     * Start Command: gunicorn app:app --bind 0.0.0.0:\$PORT"
echo "     * Plan: Free"
echo "   - Click 'Create Web Service'"
echo ""
echo "4. Add PostgreSQL Database:"
echo "   - In Render dashboard, click 'New +' → 'PostgreSQL'"
echo "   - Name: portal-db"
echo "   - Plan: Free"
echo "   - After creation, copy the 'Internal Database URL'"
echo ""
echo "5. Add Environment Variable:"
echo "   - Go to your Web Service → 'Environment' tab"
echo "   - Add: DATABASE_URI = (paste the PostgreSQL connection string)"
echo ""
echo "6. Deploy!"
echo "   - Click 'Deploy' and wait 2-5 minutes"
echo ""
echo "🎉 Your shareable URL will be: https://college-portal.onrender.com"
echo ""

